### ISSUE TITLE
Devices with same where cause Java exception (lighting + thermoregulation)

### ISSUE THREAD

**Issue by ghi820** [mvalla/openhab2-addons#43]
Have seen an issue somewhat related (I assume) to #42.
Receiving a Lighting status with the same WHERE (21 in this log extract) as a thermoregulation item results in a cast error. (in this case 21)
The Problem only seems to exist in the direction of receiving lighting and trying to cast it to thermoregulation, the other way round does not appear in the logs.
`18:48:13.149 [INFO ] [org.openwebnet.OpenGatewayBus$a     ] - MON RECEIVED  <<<<<<<<<<< *1*0*21##
Exception in thread "Thread-13033" java.lang.ClassCastException: org.openwebnet.message.Lighting cannot be cast to org.openwebnet.message.Thermoregulation
 at org.openhab.binding.openwebnet.handler.OpenWebNetThermoregulationHandler.handleMessage(OpenWebNetThermoregulationHandler.java:186)
 at org.openhab.binding.openwebnet.handler.OpenWebNetBridgeHandler.onMessage(OpenWebNetBridgeHandler.java:370)
 at org.openwebnet.OpenGatewayBus.a(OpenGatewayBus.java:259)
 at java.util.ArrayList.forEach(ArrayList.java:1257)
 at org.openwebnet.AbstractOpenGateway$1.run(AbstractOpenGateway.java:93)
 at java.lang.Thread.run(Thread.java:748)`

**Comment by mvalla** [comment]
duplicate of #42
