### ISSUE TITLE
USB dongle (gateway) cannot connect anymore

### ISSUE THREAD

**Issue by mvalla** [mvalla/openhab2-addons#66]
I have a problem with my Legrand 088328 gateway. It was working well until upgraded to 2.5.0.M2.
https://community.openhab.org/t/bticino-openwebnet-new-openhab2-binding-ready-for-testing/43377/555
```
2019-03-18 22:42:45.427 [hingStatusInfoChangedEvent] - 'openwebnet:dongle:xxxxxxx' changed from UNINITIALIZED (HANDLER_INITIALIZING_ERROR) to UNINITIALIZED
2019-03-18 22:42:48.756 [hingStatusInfoChangedEvent] - 'openwebnet:dongle:xxxxxxx' changed from UNINITIALIZED to UNINITIALIZED (DISABLED)
2019-03-18 22:42:51.675 [hingStatusInfoChangedEvent] - 'openwebnet:dongle:xxxxxxx' changed from UNINITIALIZED (DISABLED) to INITIALIZING
==> /var/log/openhab2/openhab.log <==
2019-03-18 22:42:51.671 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.openwebnet.handler.OpenWebNetBridgeHandler@95dc77': null
java.lang.NullPointerException: null
	at org.openhab.binding.openwebnet.handler.OpenWebNetBridgeHandler.ownIdFromMessage(OpenWebNetBridgeHandler.java:531) ~[?:?]
	at org.openhab.binding.openwebnet.handler.OpenWebNetBridgeHandler.testTransformations(OpenWebNetBridgeHandler.java:607) ~[?:?]
	at org.openhab.binding.openwebnet.handler.OpenWebNetBridgeHandler.initialize(OpenWebNetBridgeHandler.java:123) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.10.0.oh240]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
==> /var/log/openhab2/events.log <==
2019-03-18 22:42:51.715 [hingStatusInfoChangedEvent] - 'openwebnet:dongle:xxxxxxx' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR)
==> /var/log/openhab2/openhab.log <==
2019-03-18 22:42:51.700 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'openwebnet:dongle:xxxxxxx': null
java.lang.NullPointerException: null
	at org.openhab.binding.openwebnet.handler.OpenWebNetBridgeHandler.ownIdFromMessage(OpenWebNetBridgeHandler.java:531) ~[?:?]
	at org.openhab.binding.openwebnet.handler.OpenWebNetBridgeHandler.testTransformations(OpenWebNetBridgeHandler.java:607) ~[?:?]
	at org.openhab.binding.openwebnet.handler.OpenWebNetBridgeHandler.initialize(OpenWebNetBridgeHandler.java:123) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.10.0.oh240]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by mvalla** [comment]
fixed in 2.5.0.M2-1
